// Comprehensive Indian artist roster across Bollywood, Punjabi, regional & indie.
export const ALL_INDIAN_ARTISTS: { name: string; query: string }[] = [
  // Bollywood playback
  { name: "Arijit Singh", query: "arijit singh" },
  { name: "Shreya Ghoshal", query: "shreya ghoshal" },
  { name: "Atif Aslam", query: "atif aslam" },
  { name: "Neha Kakkar", query: "neha kakkar" },
  { name: "Pritam", query: "pritam" },
  { name: "A.R. Rahman", query: "ar rahman" },
  { name: "Jubin Nautiyal", query: "jubin nautiyal" },
  { name: "Armaan Malik", query: "armaan malik" },
  { name: "Sonu Nigam", query: "sonu nigam" },
  { name: "Kumar Sanu", query: "kumar sanu" },
  { name: "Udit Narayan", query: "udit narayan" },
  { name: "Alka Yagnik", query: "alka yagnik" },
  { name: "Lata Mangeshkar", query: "lata mangeshkar" },
  { name: "Kishore Kumar", query: "kishore kumar" },
  { name: "Mohammed Rafi", query: "mohammed rafi" },
  { name: "Asha Bhosle", query: "asha bhosle" },
  { name: "K.K.", query: "kk singer" },
  { name: "Mohit Chauhan", query: "mohit chauhan" },
  { name: "Shaan", query: "shaan singer" },
  { name: "Sunidhi Chauhan", query: "sunidhi chauhan" },
  { name: "Rahat Fateh Ali Khan", query: "rahat fateh ali khan" },
  { name: "Mohammed Irfan", query: "mohammed irfan" },
  { name: "Ankit Tiwari", query: "ankit tiwari" },
  { name: "Palak Muchhal", query: "palak muchhal" },
  { name: "Tulsi Kumar", query: "tulsi kumar" },
  { name: "Dhvani Bhanushali", query: "dhvani bhanushali" },
  { name: "Asees Kaur", query: "asees kaur" },
  { name: "Darshan Raval", query: "darshan raval" },
  { name: "Stebin Ben", query: "stebin ben" },
  { name: "Yasser Desai", query: "yasser desai" },
  { name: "Sachet Tandon", query: "sachet tandon" },
  { name: "Parampara Tandon", query: "parampara tandon" },
  { name: "Vishal Mishra", query: "vishal mishra singer" },
  { name: "Javed Ali", query: "javed ali" },
  { name: "Mika Singh", query: "mika singh" },
  { name: "Sukhwinder Singh", query: "sukhwinder singh" },
  { name: "Shilpa Rao", query: "shilpa rao" },
  { name: "Harshdeep Kaur", query: "harshdeep kaur" },
  { name: "Monali Thakur", query: "monali thakur" },
  { name: "Kanika Kapoor", query: "kanika kapoor" },
  // Punjabi / Hip-hop
  { name: "Diljit Dosanjh", query: "diljit dosanjh" },
  { name: "Honey Singh", query: "yo yo honey singh" },
  { name: "Badshah", query: "badshah rapper" },
  { name: "AP Dhillon", query: "ap dhillon" },
  { name: "Karan Aujla", query: "karan aujla" },
  { name: "Sidhu Moose Wala", query: "sidhu moose wala" },
  { name: "Shubh", query: "shubh singer" },
  { name: "Guru Randhawa", query: "guru randhawa" },
  { name: "Hardy Sandhu", query: "hardy sandhu" },
  { name: "Jass Manak", query: "jass manak" },
  { name: "Ammy Virk", query: "ammy virk" },
  { name: "Babbu Maan", query: "babbu maan" },
  { name: "Gurnam Bhullar", query: "gurnam bhullar" },
  { name: "Ranjit Bawa", query: "ranjit bawa" },
  { name: "Jasmine Sandlas", query: "jasmine sandlas" },
  { name: "Raftaar", query: "raftaar rapper" },
  { name: "Divine", query: "divine rapper" },
  { name: "Emiway Bantai", query: "emiway bantai" },
  { name: "King", query: "king rapper india" },
  { name: "MC Stan", query: "mc stan" },
  { name: "Seedhe Maut", query: "seedhe maut" },
  { name: "Krsna", query: "krsna rapper" },
  { name: "Ikka", query: "ikka rapper" },
  // Indie / Pop
  { name: "Prateek Kuhad", query: "prateek kuhad" },
  { name: "Anuv Jain", query: "anuv jain" },
  { name: "Ritviz", query: "ritviz" },
  { name: "The Local Train", query: "the local train" },
  { name: "Lucky Ali", query: "lucky ali" },
  { name: "Kailash Kher", query: "kailash kher" },
  { name: "Shreya Lenka", query: "shreya lenka" },
  { name: "Anumita Nadesan", query: "anumita nadesan" },
  // South Indian
  { name: "Sid Sriram", query: "sid sriram" },
  { name: "Anirudh Ravichander", query: "anirudh ravichander" },
  { name: "Devi Sri Prasad", query: "devi sri prasad" },
  { name: "Thaman S", query: "thaman s" },
  { name: "Yuvan Shankar Raja", query: "yuvan shankar raja" },
  { name: "Harris Jayaraj", query: "harris jayaraj" },
  { name: "Vijay Antony", query: "vijay antony" },
  { name: "Hesham Abdul Wahab", query: "hesham abdul wahab" },
  { name: "Shankar Mahadevan", query: "shankar mahadevan" },
  { name: "Hariharan", query: "hariharan singer" },
  { name: "K.S. Chithra", query: "ks chithra" },
  { name: "S.P. Balasubrahmanyam", query: "sp balasubrahmanyam" },
];
